DROP TABLE BOOK_AUTHOR;
DROP TABLE AUTHOR;
DROP TABLE BOOK_CATEGORY;
DROP TABLE REVIEW;
DROP TABLE BOOK;
DROP TABLE CATEGORY;
DROP TABLE PUBLISHER;
DROP TABLE REVIEWER;

DROP SEQUENCE BOOK_SEQ;
DROP SEQUENCE AUTHOR_SEQ;
DROP SEQUENCE PUBLISHER_SEQ;
DROP SEQUENCE REVIEWER_SEQ;
DROP SEQUENCE CATEGORY_SEQ;
DROP SEQUENCE REVIEW_SEQ;

DROP VIEW vw_book;
DROP VIEW VW_REVIEWS;
DROP VIEW VW_AUTHORS;
DROP VIEW VW_CATEGORIES;